# Generated by Django 6.0.6 on 2026-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='status',
            field=models.CharField(choices=[('answered', 'Answered'), ('clarification', 'Clarification Requested'), ('unanswered', 'Unanswered / Low Confidence'), ('rejected', 'Rejected (Gibberish/Invalid)')], default='unanswered', max_length=20),
        ),
    ]
