# Generated by Django 6.0.6 on 2026-07-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversationlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='map_query',
            field=models.CharField(blank=True, help_text="Optional: an address or place name (e.g. '1 Gombe Road, Biu, Borno State, Nigeria') to show an embedded Google Map alongside this answer. Leave blank for no map.", max_length=255),
        ),
    ]
